void main() {
  try {
    List<int> numbers = [3, 6, 7, 4];
    print(numbers[6]);
  } catch (e) {
    print("An error occurred: $e");
  }
}
